export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_FIVE_FORECAST_WEATHER = "GET_FIVE_FORECAST_WEATHER";
export const GET_GEO_INFORMATIONS = "GET_GEO_INFORMATIONS";
export const CLEAR_WEATHER_VALUES = "CLEAR_WEATHER_VALUES";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const GET_FIVEDAYS_FORECAST_ARR = "GET_FIVEDAYS_FORECAST_ARR";
export const LOADING = "LOADING";
